Query:
  type: object
  config:
    fields:
      user:
        type: "User"
        description: "Single user query"
        args:
          id:
            description: "Get user by ID"
            type: "Int!"
        resolve: "@=resolver('User', [args])"
      users:
        type: "[User!]"
        description: "List of user query"
        args:
          blocked:
            description: "is blocked ?"
            type: "Boolean"
          test:
            description: "is test ?"
            type: "Boolean"
        resolve: "@=resolver('Users', [args])"
      channels_user:
        type: "[ChannelUser!]"
        description: "List of my channels"
        resolve: "@=resolver('ChannelsUser')"
      new:
        type: "New"
        description: "Single new query"
        args:
          id:
            type: "Int!"
            description: "Get new by ID"
        resolve: "@=resolver('New', [args])"
      news:
        type: "[New!]"
        description: "List news"
        args:
          channel_id:
            type: "Int"
            description: "Get new by ID channel"
        resolve: "@=resolver('News', [args])"


