monolog:
  handlers:
    main:
      channels: ["!info", "!security", "!event", "!request"]
      type: fingers_crossed
      action_level: error
      handler: nested
      excluded_http_codes: [404, 405]
      buffer_size: 50 # How many messages should be saved? Prevent memory leaks
    nested:
      channels: ["!info", "!security", "!event", "!request"]
      type: rotating_file
      max_files: 0
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: CRITICAL
    debug_app:
      channels: ['!info', '!security', "!event", '!php']
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%_debug.log"
      level: DEBUG
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]
